# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

# linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  # rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
exclude:
    - build/**
    - test/**
    - sdk/**
    - lib/**.g.dart
    - lib/*/**.g.dart
    - lib/**/gen/**
    - lib/4d/flutter_blue/**
  
errors:
    lines_longer_than_80_chars: warning
    missing_return: error
    dead_code: error
    always_declare_return_types: error
    avoid_web_libraries_in_flutter: error
    missing_required_param: error
    file_names: error
    camel_case_types: error
    empty_statements: error
    iterable_contains_unrelated_type: error
    list_remove_unrelated_type: error
    no_duplicate_case_values: error
    unrelated_type_equality_checks: error
    type_annotate_public_apis: error
    unnecessary_new: error
    prefer_single_quotes: error
    null_check_on_nullable_type_parameter: error
    hash_and_equals: error

linter:
  rules:
    always_declare_return_types: true
    always_require_non_null_named_parameters: true
    annotate_overrides: true
    avoid_annotating_with_dynamic: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    close_sinks: true
    constant_identifier_names: false
    empty_statements: true
    file_names: true
    hash_and_equals: true
    iterable_contains_unrelated_type: true
    lines_longer_than_80_chars: false
    list_remove_unrelated_type: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    omit_local_variable_types: false
    only_throw_errors: true
    prefer_collection_literals: true
    prefer_contains: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
    prefer_single_quotes: true
    prefer_void_to_null: true
    sized_box_for_whitespace: true
    sort_pub_dependencies: false
    unnecessary_await_in_return: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_statements: true
    unnecessary_this: false
    unrelated_type_equality_checks: true
    use_key_in_widget_constructors: true
    unnecessary_string_interpolations: true
    sort_child_properties_last: true
    avoid_private_typedef_functions: true
    avoid_print: false
    avoid_return_types_on_setters: true
    type_annotate_public_apis: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    prefer_relative_imports: false
    prefer_interpolation_to_compose_strings: true
    avoid_function_literals_in_foreach_calls: false
    join_return_with_assignment: true
    unused_field: true
    unused_import: true
    unnecessary_import: true
    null_check_on_nullable_type_parameter: true
    use_late_for_private_fields_and_variables: true
    cast_nullable_to_non_nullable: true
    unnecessary_nullable_for_final_variable_declarations: true
    use_if_null_to_convert_nulls_to_bools: true
    unnecessary_null_checks: true
    use_raw_strings: true
    flutter_style_todos: true
    noop_primitive_operations: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_renaming_method_parameters: true
    avoid_returning_null_for_void: true
    avoid_single_cascade_in_expression_statements: true
    control_flow_in_finally: true
    empty_constructor_bodies: true
    exhaustive_cases: true
    implementation_imports: true
    library_names: true
    library_prefixes: true
    null_closures: true
    overridden_fields: true
    package_names: true
    prefer_adjacent_string_concatenation: true
    prefer_conditional_assignment: true
    prefer_equal_for_default_values: true
    prefer_function_declarations_over_variables: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_is_not_operator: true
    prefer_spread_collections: true
    recursive_getters: true
    slash_for_doc_comments: true
    type_init_formals: true
    unnecessary_brace_in_string_interps: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_string_escapes: true
    use_function_type_syntax_for_parameters: true
    use_rethrow_when_possible: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    camel_case_extensions: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    non_constant_identifier_names: true
    package_prefixed_library_names: true
    prefer_generic_function_type_aliases: true
    prefer_iterable_whereType: true
    prefer_typing_uninitialized_variables: true
    provide_deprecation_message: true
    valid_regexps: true
    void_checks: true
    use_decorated_box: true

    use_full_hex_values_for_flutter_colors: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    invariant_booleans: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    test_types_in_equals: true
    throw_in_finally: true
    unsafe_html: true
    #use_build_context_synchronously: true
    #always_put_control_body_on_new_line: true
    #always_put_required_named_parameters_first: true

    avoid_catching_errors: true
    #avoid_classes_with_only_static_members: true
    avoid_double_and_int_checks: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_escaping_inner_quotes: true
    avoid_field_initializers_in_const_classes: true
    avoid_final_parameters: true
    avoid_implementing_value_types: true
    avoid_multiple_declarations_per_line: true
    #avoid_positional_boolean_parameters: true
    avoid_returning_null: true
    avoid_returning_this: true
    #avoid_setters_without_getters: true
    avoid_types_on_closure_parameters: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    #cascade_invocations: true
    deprecated_consistency: true
    directives_ordering: true
    do_not_use_environment: true
    eol_at_end_of_file: true
    leading_newlines_in_multiline_strings: true
    no_leading_underscores_for_local_identifiers: false
    no_runtimeType_toString: true
    prefer_asserts_in_initializer_lists: true
    prefer_constructors_over_static_methods: true
    prefer_expression_function_bodies: false
    prefer_if_elements_to_conditional_expressions: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_null_aware_method_calls: true
    #require_trailing_commas: false
    sized_box_shrink_expand: true
    super_goes_last: true
    tighten_type_of_initializing_formals: true
    #unawaited_futures: true
    unnecessary_constructor_name: true
    unnecessary_null_aware_assignments: true
    use_is_even_rather_than_modulo: true
    #use_setters_to_change_properties: true
    use_string_buffers: true
    use_to_and_as_if_applicable: true
    parameter_assignments: true

